# Generated by Django 5.1.13 on 2026-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csrms_api', '0002_requestupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('sensor_type', models.CharField(max_length=24)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='alert_key',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
